{
  "modified": "2023-08-28T16:57:11Z",
  "published": "2023-08-22T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2022-48564",
  "aliases": [
    "PSF-2023-10",
    "GHSA-p8vw-m6qq-w42v"
  ],
  "details": "read_ints in plistlib.py in Python through 3.9.1 is vulnerable to a potential DoS attack via CPU and RAM exhaustion when processing malformed Apple Property List files in binary format.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.7.10"
            },
            {
              "introduced": "3.8.0-alpha1"
            },
            {
              "fixed": "3.8.7-rc1"
            },
            {
              "introduced": "3.9.0-alpha1"
            },
            {
              "fixed": "3.9.1-rc1"
            },
            {
              "introduced": "3.10.0-alpha1"
            },
            {
              "fixed": "3.10.0-alpha2"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://www.cve.org/CVERecord?id=CVE-2022-48564"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue42103"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/pull/22882"
    }
  ]
}