{
  "modified": "2023-08-25T16:05:33Z",
  "published": "2020-10-22T02:47:40Z",
  "schema_version": "1.5.0",
  "id": "CVE-2020-27619",
  "aliases": [
    "PSF-2020-6"
  ],
  "details": "In Python 3 through 3.9.0, the Lib/test/multibytecodec_support.py CJK codec tests call eval() on content retrieved via HTTP.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.6.0"
            },
            {
              "fixed": "3.6.13"
            },
            {
              "introduced": "3.7.0"
            },
            {
              "fixed": "3.7.10"
            },
            {
              "introduced": "3.8.0"
            },
            {
              "fixed": "3.8.7"
            },
            {
              "introduced": "3.9.0"
            },
            {
              "fixed": "3.9.1"
            },
            {
              "fixed": "3.10.0-alpha2"
            },
            {
              "introduced": "3.10.0"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/security/cve/CVE-2020-27619"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue41944"
    }
  ]
}